import Head from 'next/head';
import Image from 'next/image';
import imageSite from '../public/notfound.svg';
export default function NotFound() {
 
  return (
    <div>
      <Head>
        <title>Wallet Ng-Cash App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-end gap-44 m-2">
        <div className="flex items-center">
          <h1 className="text-black text-center">404: Not Found</h1>
        </div>
        <Image className="" src={imageSite} alt="Logo NG" />
        {/* <div className="flex flex-col gap-3 items-center self-center">
          </div> */}
      </main>
    </div>
  );
}