import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Logo from '../public/logo_ng.png';

import { loadStripe } from '@stripe/stripe-js';

const stripe = await loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!);


interface IEmail {
  email: string;
}
export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleEmail = ({ email }: IEmail) => {
    setEmail(email);
  };
  console.log(email);

  return (
    <div className="h-full">
      <Head>
        <title>Ng-Cash App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black flex justify-center items-center w-full">
        <form className="border-2 rounded-xl	flex items-center flex-col p-20 gap-3">
          <Image src={Logo} className="w-1/2" alt="Logo NG" />
          <input
            className="w-11/12 content-center border-2 text-center"
            type="email"
            placeholder="E-mail"
            value={email}
          />
          <input
            className="w-11/12 border-2 text-center"
            type="password"
            placeholder="Password"
            value={password}
          />
          <button
            className="rounded-full bg-indigo-700 w-11/12	 mt-6 p-1 hover:bg-indigo-500 text-neutral-50	"
            type="submit"
          >
            Sign In
          </button>
          <button
            className="rounded-full bg-lime-700 hover:bg-lime-500 text-neutral-50	 w-11/12 p-1"
            type="submit"
          >
            Sign Up
          </button>
        </form>
      </main>
    </div>
  );
}
