import Head from 'next/head';
import Link from 'next/link';
import TransactionsTable from '../src/components/TransactionsTable';

export default function Wallet() {
 
  return (
    <div>
      <Head>
        <title>Wallet Ng-Cash App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="flex justify-end gap-5 m-2 color-white">
         <Link rel="/" href={'/wallet'}>My Balance: $4.000</Link>
          <Link rel="/" href={'/'}>Log Out</Link>

        </nav>
        <TransactionsTable />
        
      </main>
    </div>
  );
}